import Head from "next/head";
import Image from "next/image";
import { useCallback, useState } from "react";
import { Inter } from "next/font/google";
import { Card, Input, Button, Typography } from "@material-tailwind/react";
import { useGoogleReCaptcha } from "react-google-recaptcha-v3";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { executeRecaptcha } = useGoogleReCaptcha();
  const [sent, setSent] = useState(false);

  const handleSubmit = useCallback(
    (e) => {
      e.preventDefault();
      if (!executeRecaptcha) {
        console.log("Execute recaptcha not yet available");
        return;
      }

      executeRecaptcha("formSubmit").then(async (gReCaptchaToken) => {
        console.log(gReCaptchaToken, "response Google reCaptcha server");

        const form = e.target as HTMLFormElement;
        const params = {
          phoneNumber: form.phoneNumber.value as string,
          recaptchaToken: gReCaptchaToken,
        };

        const response = await fetch("api/phone-calls", {
          body: JSON.stringify(params),
          headers: {
            "Content-Type": "application/json",
          },
          method: "POST",
        });

        if (response.status == 200) {
          setSent(true);
        } else {
        }
      });
    },
    [executeRecaptcha]
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="bg-white">
          <div className="layout flex min-h-screen flex-col items-center justify-center text-center">
            {sent && (
              <Typography variant="h1" color="green">
                Sent
              </Typography>
            )}

            <Card color="transparent" shadow={false}>
              <Typography variant="h1" color="blue-gray">
                Demo
              </Typography>
              <Typography color="gray" className="mt-1 font-normal">
                Enter your phone number to receive calls.
              </Typography>
              <form className="mt-8 mb-2 w-80 max-w-screen-lg sm:w-96" onSubmit={handleSubmit}>
                <div className="mb-4 flex flex-col gap-6">
                  <Input size="lg" name="phoneNumber" label="Phone Number" />
                </div>
                <Button type="submit" className="mt-6" fullWidth>
                  Submit
                </Button>
              </form>
            </Card>
          </div>
        </section>
      </main>
    </>
  );
}
